import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableRow,
  TableCell,
  TextRun,
  WidthType,
  AlignmentType,
  HeadingLevel,
  PageBreak,
} from 'docx';
import { saveAs } from 'file-saver';
import type { ProcessedMagStation } from './magneticCalculations';
import {
  computeReductionToPole,
  computeMagDerivatives,
  computeMagPowerSpectrum,
  computeInclination,
} from './magneticCalculations';

const BRAND_RED = 'E31E24';
const BRAND_DARK = '1A1A2E';
const FONT = 'Calibri';

// ─── Cell helpers ────────────────────────────────────────────────────────────

function headerCell(text: string, width = 700): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        children: [new TextRun({ text, bold: true, size: 15, color: 'FFFFFF', font: FONT })],
        alignment: AlignmentType.CENTER,
      }),
    ],
    shading: { fill: BRAND_RED },
    width: { size: width, type: WidthType.DXA },
  });
}

function dataCell(text: string, width = 700): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        children: [new TextRun({ text, size: 15, font: FONT })],
        alignment: AlignmentType.CENTER,
      }),
    ],
    width: { size: width, type: WidthType.DXA },
  });
}

function subHeaderCell(text: string): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        children: [new TextRun({ text, bold: true, size: 15, color: 'FFFFFF', font: FONT })],
        alignment: AlignmentType.CENTER,
      }),
    ],
    shading: { fill: BRAND_DARK },
  });
}

function heading(text: string, level: typeof HeadingLevel[keyof typeof HeadingLevel] = HeadingLevel.HEADING_2) {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, size: 24, color: BRAND_DARK, font: FONT })],
    heading: level,
    spacing: { before: 300, after: 150 },
  });
}

function body(text: string, opts?: { bold?: boolean; italic?: boolean }) {
  return new Paragraph({
    children: [new TextRun({ text, size: 18, font: FONT, bold: opts?.bold, italics: opts?.italic })],
    spacing: { after: 80 },
  });
}

function bullet(text: string) {
  return new Paragraph({
    children: [new TextRun({ text: `• ${text}`, size: 18, font: FONT })],
    spacing: { after: 60 },
  });
}

function spacer() {
  return new Paragraph({ children: [new TextRun({ text: '', size: 16 })], spacing: { before: 200 } });
}

function computeStats(values: number[]) {
  const n = values.length;
  if (n === 0) return { min: 0, max: 0, mean: 0, std: 0 };
  const min = Math.min(...values);
  const max = Math.max(...values);
  const mean = values.reduce((a, b) => a + b, 0) / n;
  const std = Math.sqrt(values.reduce((a, b) => a + (b - mean) ** 2, 0) / n);
  return { min, max, mean, std };
}

function statsRow(label: string, stats: { min: number; max: number; mean: number; std: number }) {
  return new TableRow({
    children: [
      dataCell(label),
      dataCell(stats.min.toFixed(3)),
      dataCell(stats.max.toFixed(3)),
      dataCell(stats.mean.toFixed(3)),
      dataCell(stats.std.toFixed(3)),
    ],
  });
}

// ─── Main export ─────────────────────────────────────────────────────────────

export interface MagReportOptions {
  includeAdvanced?: boolean;
  latitude?: number;
}

export async function generateMagneticReport(
  data: ProcessedMagStation[],
  projectName: string,
  options: MagReportOptions = {}
): Promise<void> {
  const { includeAdvanced = true, latitude } = options;
  const reportData = data.filter(d => !d.remark?.toLowerCase().includes('base'));
  const now = new Date();

  // ─── Title page ────────────────────────────────────────────────────────────
  const titleSection = [
    new Paragraph({ spacing: { before: 2000 }, children: [] }),
    new Paragraph({
      children: [new TextRun({ text: 'MAGNETIC DATA REDUCTION', bold: true, size: 48, color: BRAND_RED, font: FONT })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: '& INTERPRETATION REPORT', bold: true, size: 40, color: BRAND_DARK, font: FONT })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [new TextRun({ text: projectName, size: 28, color: BRAND_DARK, font: FONT })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: `Date: ${now.toLocaleDateString()}`, size: 22, font: FONT })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: `Stations: ${reportData.length}`, size: 20, font: FONT })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Generated by Geotech4All Magnetic WebApp', italics: true, size: 18, color: BRAND_RED, font: FONT })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({ children: [new PageBreak()] }),
  ];

  // ─── Survey metadata ──────────────────────────────────────────────────────
  const hasCoords = reportData.some(s => s.latitude && s.longitude);
  const metadataSection = [
    heading('1. Survey Metadata'),
    body(`Project Name: ${projectName}`, { bold: true }),
    body(`Report Date: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`),
    body(`Number of Stations: ${reportData.length}`),
    spacer(),
  ];

  if (hasCoords) {
    const lats = reportData.filter(s => s.latitude).map(s => s.latitude!);
    const lons = reportData.filter(s => s.longitude).map(s => s.longitude!);
    const latStats = computeStats(lats);
    const lonStats = computeStats(lons);
    metadataSection.push(
      body('Survey Area Extent:', { bold: true }),
      bullet(`Latitude: ${latStats.min.toFixed(5)}° to ${latStats.max.toFixed(5)}°`),
      bullet(`Longitude: ${lonStats.min.toFixed(5)}° to ${lonStats.max.toFixed(5)}°`),
      spacer(),
    );
  }

  // ─── Statistical summary ──────────────────────────────────────────────────
  const totalFieldStats = computeStats(reportData.map(s => s.averageNT));
  const anomalyStats = computeStats(reportData.map(s => s.totalAnomaly));
  const driftStats = computeStats(reportData.map(s => s.driftCorrection));
  const diurnalStats = computeStats(reportData.map(s => s.diurnalCorrection));
  const igrfStats = computeStats(reportData.map(s => s.igrfField));

  const statsTable = new Table({
    rows: [
      new TableRow({
        children: [subHeaderCell('Parameter'), subHeaderCell('Min'), subHeaderCell('Max'), subHeaderCell('Mean'), subHeaderCell('Std Dev')],
      }),
      statsRow('Total Field (nT)', totalFieldStats),
      statsRow('Total Anomaly (nT)', anomalyStats),
      statsRow('Drift Correction (nT)', driftStats),
      statsRow('Diurnal Correction (nT)', diurnalStats),
      statsRow('IGRF Field (nT)', igrfStats),
    ],
    width: { size: 100, type: WidthType.PERCENTAGE },
  });

  const statsSection = [
    heading('2. Statistical Summary'),
    statsTable,
    spacer(),
  ];

  // ─── Main data table ──────────────────────────────────────────────────────
  const mainTableHeader = new TableRow({
    children: [
      headerCell('S/N'), headerCell('Dist (m)'), headerCell('Avg nT'),
      headerCell('Drift'), headerCell('Diurnal'), headerCell('IGRF'),
      headerCell('Regional'), headerCell('Reduced'), headerCell('Total Anomaly'),
    ],
  });

  const mainDataRows = reportData.map((s, i) =>
    new TableRow({
      children: [
        dataCell(String(i + 1)),
        dataCell(s.distance.toFixed(1)),
        dataCell(s.averageNT.toFixed(2)),
        dataCell(s.driftCorrection.toFixed(4)),
        dataCell(s.diurnalCorrection.toFixed(4)),
        dataCell(s.igrfField.toFixed(2)),
        dataCell(s.regionalField.toFixed(2)),
        dataCell(s.reducedValue.toFixed(3)),
        dataCell(s.totalAnomaly.toFixed(3)),
      ],
    })
  );

  const dataTableSection = [
    heading('3. Processed Magnetic Data'),
    body('Corrections applied: Drift (linear), Diurnal, IGRF reference, Regional removal.'),
    new Table({
      rows: [mainTableHeader, ...mainDataRows],
      width: { size: 100, type: WidthType.PERCENTAGE },
    }),
    new Paragraph({ children: [new PageBreak()] }),
  ];

  // ─── Advanced interpretation ──────────────────────────────────────────────
  let advancedSection: (Paragraph | Table)[] = [];

  if (includeAdvanced && reportData.length >= 4) {
    const coordStations = reportData.filter(s => s.latitude);
    const avgLat = latitude ?? (coordStations.length > 0 ? coordStations.map(s => s.latitude!).reduce((a, b) => a + b, 0) / coordStations.length : 7.0);
    const inclination = computeInclination(avgLat);

    // RTP
    const rtpResults = computeReductionToPole(reportData, inclination);
    const rtpHeader = new TableRow({
      children: [headerCell('S/N'), headerCell('Dist (m)'), headerCell('Original (nT)'), headerCell('RTP (nT)')],
    });
    const rtpRows = rtpResults.map(r => new TableRow({
      children: [dataCell(String(r.sn)), dataCell(r.distance.toFixed(1)), dataCell(r.original.toFixed(3)), dataCell(r.rtpValue.toFixed(3))],
    }));

    // Derivatives
    const derivResults = computeMagDerivatives(reportData);
    const derHeader = new TableRow({
      children: [headerCell('S/N'), headerCell('Dist (m)'), headerCell('dT/dx'), headerCell('d²T/dz²'), headerCell('|AS|')],
    });
    const derRows = derivResults.map(r => new TableRow({
      children: [
        dataCell(String(r.sn)), dataCell(r.distance.toFixed(1)),
        dataCell(r.horizontalGradient.toFixed(4)), dataCell(r.verticalGradient.toFixed(4)),
        dataCell(r.analyticSignal.toFixed(4)),
      ],
    }));

    // Power Spectrum
    const { depthEstimates } = computeMagPowerSpectrum(reportData);

    advancedSection = [
      heading('4. Advanced Interpretation'),

      heading('4.1 Reduction to Pole (RTP)', HeadingLevel.HEADING_3),
      body(`Inclination: ${inclination.toFixed(2)}°  |  Declination: 0°`),
      spacer(),
      new Table({ rows: [rtpHeader, ...rtpRows], width: { size: 100, type: WidthType.PERCENTAGE } }),
      new Paragraph({ children: [new PageBreak()] }),

      heading('4.2 Derivative Analysis', HeadingLevel.HEADING_3),
      body('Horizontal gradient (dT/dx) delineates lateral boundaries of magnetic sources.'),
      body('Analytic signal amplitude |AS| locates source edges independent of magnetization direction.'),
      spacer(),
      new Table({ rows: [derHeader, ...derRows], width: { size: 100, type: WidthType.PERCENTAGE } }),
      spacer(),

      heading('4.3 Power Spectrum Depth Estimates', HeadingLevel.HEADING_3),
      body(`Estimated Deep Source Depth: ~${depthEstimates.deep.toFixed(2)} km`, { bold: true }),
      body(`Estimated Shallow Source Depth: ~${depthEstimates.shallow.toFixed(2)} km`, { bold: true }),
      spacer(),
      body('Depth estimation derived from the slope of ln(Power) vs. wavenumber.'),
      new Paragraph({ children: [new PageBreak()] }),
    ];
  }

  // ─── Methodology ──────────────────────────────────────────────────────────
  const methodNum = includeAdvanced ? '5' : '4';
  const methodSection = [
    heading(`${methodNum}. Methodology & Formulas`),
    heading('Magnetic Reduction', HeadingLevel.HEADING_3),
    bullet('IGRF Reference: Simplified dipole model (13th generation approximation)'),
    bullet('Diurnal Correction: Interpolated from base station readings or sinusoidal model'),
    bullet('Drift Correction: Linear drift factor applied over time'),
    bullet('Regional Removal: Subtraction of regional magnetic field estimate'),
    bullet('Total Anomaly = Observed - IGRF - Diurnal - Drift'),
    spacer(),
  ];

  if (includeAdvanced) {
    methodSection.push(
      heading('Advanced Methods', HeadingLevel.HEADING_3),
      bullet('Reduction to Pole (RTP): Wavenumber-domain phase rotation using magnetic inclination/declination'),
      bullet('Horizontal Gradient: Central finite differences dT/dx'),
      bullet('Vertical Gradient: Second derivative proxy d²T/dz²'),
      bullet('Analytic Signal: |AS| = √((dT/dx)² + (dT/dz)²)'),
      bullet('Power Spectrum: DFT with depth estimation from ln(Power) slope'),
      spacer(),
    );
  }

  // ─── Footer ────────────────────────────────────────────────────────────────
  const footer = [
    spacer(),
    new Paragraph({
      children: [new TextRun({ text: '─'.repeat(60), size: 16, color: BRAND_RED, font: FONT })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Generated by Geotech4All Magnetic WebApp — www.geotech4all.com', italics: true, size: 16, color: BRAND_RED, font: FONT })],
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: `© ${now.getFullYear()} Geotech4All. All rights reserved.`, size: 14, color: BRAND_DARK, font: FONT })],
      alignment: AlignmentType.CENTER,
    }),
  ];

  // ─── Assemble ──────────────────────────────────────────────────────────────
  const doc = new Document({
    sections: [
      {
        properties: { page: { size: { orientation: 'landscape' as any } } },
        children: [
          ...titleSection,
          ...metadataSection,
          ...statsSection,
          ...dataTableSection,
          ...advancedSection,
          ...methodSection,
          ...footer,
        ] as any[],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${projectName.replace(/\s+/g, '_')}_Magnetic_Report.docx`);
}
